spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commercial?user=root&password=teste123*&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
   